# Generated by Django 5.2.8 on 2025-11-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_user',
            name='is_user_a_test_user',
            field=models.BooleanField(default=False),
        ),
    ]
