# Generated by Django 5.0.14 on 2025-12-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="base_user",
            name="favorite_books",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="products.products"
            ),
        ),
    ]
