# Generated by Django 5.0.14 on 2025-11-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_user',
            name='user_owned_books',
            field=models.JSONField(default=list),
        ),
    ]
