# Generated by Django 5.0.14 on 2025-11-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_base_user_is_user_a_test_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="base_user",
            name="favorite_genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fantasy", "Fantasy"),
                    ("scifi", "Science Fiction"),
                    ("mystery", "Mystery"),
                    ("romance", "Romance"),
                    ("nonfiction", "Non-Fiction"),
                    ("horror", "Horror"),
                    ("history", "History"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
