# Generated by Django 5.0.14 on 2025-11-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_base_user_favorite_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="base_user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
