# Generated by Django 5.0.14 on 2025-11-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_base_user_favorite_genre_base_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="base_user",
            name="favorite_authors",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
