# Generated by Django 5.2.8 on 2025-11-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_base_user_favorite_authors'),
        ('products', '0003_delete_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_user',
            name='user_owned_products',
            field=models.ManyToManyField(to='products.products'),
        ),
    ]
