# Generated by Django 5.0.14 on 2025-12-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_base_user_user_owned_products"),
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="base_user",
            name="user_tags",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="general.tag"
            ),
        ),
    ]
