# Generated by Django 5.2.8 on 2025-12-04 18:21

import django.db.models.deletion
import reviews.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=reviews.models.today_date)),
                ('review_text', models.TextField(blank=True, default='')),
                ('review_tags', models.JSONField(blank=True, default=list)),
                ('trigger_warnings', models.JSONField(blank=True, default=list)),
                ('star_rating', models.PositiveSmallIntegerField(default=1)),
                ('spice_rating', models.PositiveSmallIntegerField(default=1)),
                ('violence_rating', models.PositiveSmallIntegerField(default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.products')),
            ],
        ),
    ]
