# Generated by Django 5.0.14 on 2025-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
