# Generated by Django 5.0.14 on 2025-11-27 01:05

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateField(default=reviews.models.today_date),
        ),
    ]
