# Generated by Django 5.2.8 on 2025-12-04 18:21

import django.db.models.deletion
import general.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='forum_post',
            fields=[
                ('approved', models.BooleanField(default=True)),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_text', models.TextField(blank=True, null=True, validators=[general.validators.Validators.is_any_word_in_text_profanity])),
                ('post_reactions', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='forum_comment',
            fields=[
                ('approved', models.BooleanField(default=True)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(validators=[general.validators.Validators.is_any_word_in_text_profanity])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forums.forum_post')),
            ],
        ),
        migrations.CreateModel(
            name='forums',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('forum_name', models.TextField()),
                ('forum_description', models.TextField(validators=[general.validators.Validators.is_any_word_in_text_profanity])),
                ('forum_tags', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('meeting_day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10)),
                ('meeting_time', models.TimeField()),
                ('forum_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forum_tags_m2m', models.ManyToManyField(blank=True, related_name='forums', to='general.tag')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums_about_this_book', to='products.products')),
            ],
        ),
        migrations.AddField(
            model_name='forum_post',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forums.forums'),
        ),
    ]
