# Generated by Django 5.0.14 on 2025-11-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum_post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_reactions', models.JSONField(default=list)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.base_user')),
            ],
        ),
        migrations.CreateModel(
            name='forums',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('forum_name', models.TextField()),
                ('forum_description', models.TextField()),
                ('forum_tags', models.JSONField(default=list)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.base_user')),
            ],
        ),
    ]
