# Generated by Django 5.0.14 on 2025-11-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forums",
            old_name="owner",
            new_name="forum_lead",
        ),
        migrations.AlterField(
            model_name="forums",
            name="meeting_day",
            field=models.CharField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thu", "Thursday"),
                    ("Fri", "Friday"),
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="forums",
            name="meeting_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="forums",
            name="start_date",
            field=models.DateField(),
        ),
    ]
