# Generated by Django 5.2.8 on 2025-11-20 15:26

import general.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_rename_owner_forums_forum_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_comment',
            name='comment_text',
            field=models.TextField(validators=[general.validators.Validators.is_any_word_in_text_profanity]),
        ),
        migrations.AlterField(
            model_name='forum_post',
            name='post_text',
            field=models.TextField(blank=True, null=True, validators=[general.validators.Validators.is_any_word_in_text_profanity]),
        ),
        migrations.AlterField(
            model_name='forums',
            name='forum_description',
            field=models.TextField(validators=[general.validators.Validators.is_any_word_in_text_profanity]),
        ),
    ]
