# Generated by Django 5.2.8 on 2025-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_alter_forum_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='post_reactions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
