# Generated by Django 5.0.14 on 2025-11-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0004_alter_forum_post_post_reactions"),
        ("products", "0002_product_review_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="forums",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forums_about_this_book",
                to="products.products",
            ),
        ),
    ]
