# Generated by Django 5.0.14 on 2025-11-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0005_forums_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum_post",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
