# Generated by Django 5.0.14 on 2025-11-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0006_forum_post_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum_comment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
