# Generated by Django 5.0.14 on 2025-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0007_forum_comment_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum_comment",
            name="approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="forum_post",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
