# Generated by Django 5.0.14 on 2025-12-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0008_alter_forum_comment_approved_and_more"),
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forums",
            name="forum_tags_m2m",
            field=models.ManyToManyField(
                blank=True, related_name="forums", to="general.tag"
            ),
        ),
    ]
