# Generated by Django 5.2.8 on 2025-11-16 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_stripe_id', models.TextField(default='PLACE_HOLDER')),
                ('product_name', models.TextField()),
                ('product_link', models.TextField()),
                ('product_description', models.TextField()),
                ('product_price', models.FloatField()),
                ('product_tags', models.JSONField(default=list)),
                ('product_text', models.TextField()),
                ('product_images', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='product_review',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_reactions', models.JSONField(default=list)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_being_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
