# Generated by Django 5.0.14 on 2025-11-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('prodcut_name', models.TextField()),
                ('prodcut_link', models.TextField()),
                ('product_discription', models.TextField()),
                ('product_price', models.FloatField()),
                ('prodcut_tags', models.JSONField(default=list)),
                ('product_text', models.TextField()),
                ('product_images', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='product_review',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_reactions', models.JSONField(default=list)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.base_user')),
                ('product_being_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
