# Generated by Django 5.2.8 on 2025-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_stripe_id', models.TextField(default='PLACE_HOLDER')),
                ('product_name', models.TextField()),
                ('product_link', models.TextField()),
                ('product_description', models.TextField()),
                ('product_price', models.FloatField()),
                ('product_tags', models.JSONField(default=list)),
                ('product_text', models.TextField()),
                ('product_images', models.JSONField(default=list)),
                ('product_tags_m2m', models.ManyToManyField(blank=True, related_name='products', to='general.tag')),
            ],
        ),
    ]
