# Generated by Django 5.2.5 on 2025-11-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="prodcut_stripe_id",
            field=models.TextField(default="PLACE_HOLDER"),
        ),
    ]
