# Generated by Django 5.0.14 on 2025-11-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_review",
            name="post_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
