# Generated by Django 5.2.8 on 2025-11-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_review_post_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_review',
        ),
    ]
