# Generated by Django 5.0.14 on 2025-12-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
        ("products", "0003_delete_product_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="product_tags_m2m",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="general.tag"
            ),
        ),
    ]
